<?php
// $Id$
/**
 * @file
 * Show a block with actual date, name day and holiday if exists
 */

/**
 * Implementation of hook_block().
 */

function nameday_block($op = 'list', $delta = '', $edit = array()) {
  dfb("asdasdasd");
  $blocks = array();
  switch ($op) {
    case 'list':
      $blocks[0]['info'] = "Name day";
      return $blocks;
    case 'configure':
      $form['show_date'] = array(
        '#type' => 'checkbox',
        '#title' => 'Show date in the block',
        '#default_value' => variable_get('show_date',  TRUE),
      );
      return $form;
    case 'save':
      variable_set('show_date', $edit['show_date']);
      return ;
    case 'view':
      $block['subject'] = t('Name day');
      $block['content'] = nameday_block_content();
      return $block;

  }
}

/**
 * Implementation of hook_theme().
 */

function nameday_theme() {
  return array(
    'nameday' => array(
      'arguments' => array('nameday' => NULL, 'holiday' => NULL, 'date' => TRUE),
      'template' => 'nameday',
    )
  );
}

/**
 * returns the nameday
 */
function  nameday_block_content() {
  $lang = $GLOBALS["language"]->language;
  $date = getdate();
  $result = db_fetch_array(db_query("SELECT * FROM {nameday} WHERE month=%d AND day=%d AND language='%s'", $date["mon"], $date["mday"], $lang));
  $nameday = $result["name"];
  $holiday = $result["holiday"];
  return theme('nameday', $nameday, $holiday, variable_get('show_date',  TRUE));
}
